### ISSUE TITLE
Crashing when trying to save icns file

### ISSUE THREAD

**Issue by bigethan** [alptugan/icns-creator#1]
Hello, I tried using this on an M2 running MacOS 14 (Sonoma), and it crashes when going to save out the files from a png (attached). Crash Log in case it helps:

<details><summary>Full crash log</summary>
<pre>
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               icns creator [26948]
Path:                  /Applications/icns creator.app/Contents/MacOS/icns creator
Identifier:            com.alptugan.icns-creator
Version:               1.2 (1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-10-11 18:50:58.4077 -0700
OS Version:            macOS 14.0 (23A344)
Report Version:        12
Anonymous UUID:        2E52B21F-E5AD-9BDE-FAB5-61642DAD7A07

Sleep/Wake UUID:       3A619A88-4944-4894-859F-11CD2EEBF295

Time Awake Since Boot: 270000 seconds
Time Since Wake:       7568 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x0000000104c2d67c

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [26948]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   icns creator                  	       0x104c2d67c 0x104c24000 + 38524
1   icns creator                  	       0x104c2c99c 0x104c24000 + 35228
2   SwiftUI                       	       0x1b4612188 0x1b2d4e000 + 25969032
3   SwiftUI                       	       0x1b3f18da0 0x1b2d4e000 + 18656672
4   SwiftUI                       	       0x1b3f377e0 0x1b2d4e000 + 18782176
5   SwiftUI                       	       0x1b3db5bd0 0x1b2d4e000 + 17202128
6   SwiftUI                       	       0x1b45ffd84 0x1b2d4e000 + 25894276
7   SwiftUI                       	       0x1b45ff53c 0x1b2d4e000 + 25892156
8   SwiftUI                       	       0x1b3f1f190 0x1b2d4e000 + 18682256
9   SwiftUI                       	       0x1b3f1f284 0x1b2d4e000 + 18682500
10  AppKit                        	       0x18c06a68c -[NSApplication(NSResponder) sendAction:to:from:] + 460
11  AppKit                        	       0x18c3cb4d4 __40-[NSControl _sendActionsForEvents:view:]_block_invoke + 216
12  AppKit                        	       0x18c3cb3ac -[NSControl _sendActionsForEvents:view:] + 216
13  AppKit                        	       0x18c0678d8 NSControlTrackMouse + 1616
14  AppKit                        	       0x18c06725c -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 144
15  AppKit                        	       0x18c067114 -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 488
16  AppKit                        	       0x18c0665e8 -[NSControl mouseDown:] + 448
17  AppKit                        	       0x18c0653b4 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 3472
18  AppKit                        	       0x18bff0b6c -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 364
19  AppKit                        	       0x18bff082c -[NSWindow(NSEventRouting) sendEvent:] + 284
20  AppKit                        	       0x18c697c08 -[NSApplication(NSEventRouting) sendEvent:] + 1556
21  AppKit                        	       0x18c2eb1bc -[NSApplication _handleEvent:] + 60
22  AppKit                        	       0x18beb8460 -[NSApplication run] + 512
23  AppKit                        	       0x18be8f708 NSApplicationMain + 880
24  SwiftUI                       	       0x1b2e25944 0x1b2d4e000 + 883012
25  SwiftUI                       	       0x1b36af014 0x1b2d4e000 + 9834516
26  SwiftUI                       	       0x1b3ac945c 0x1b2d4e000 + 14136412
27  icns creator                  	       0x104c2e0d4 0x104c24000 + 41172
28  dyld                          	       0x188295058 start + 2224

Thread 1:
0   libsystem_pthread.dylib       	       0x188609e28 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x188609e28 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x188609e28 start_wqthread + 0

Thread 4:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1885ce8b4 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1885e0d30 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1885d74f0 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x1885cec38 mach_msg + 24
4   CoreFoundation                	       0x1886ebed0 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1886ea798 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1886e9c2c CFRunLoopRunSpecific + 608
7   AppKit                        	       0x18bfee8e0 _NSEventThread + 144
8   libsystem_pthread.dylib       	       0x18860f034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x188609e3c thread_start + 8

Thread 5:
0   libsystem_pthread.dylib       	       0x188609e28 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x188609e28 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000000016b1da220   x1: 0x0000001800000003   x2: 0x0000000000000001   x3: 0x0000000000000001
    x4: 0x0000001200000003   x5: 0x0000000000000001   x6: 0x0000000000000000   x7: 0x0000000000000001
    x8: 0xfffffffe00000000   x9: 0x0000001800000003  x10: 0x0000001600000003  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000010  x14: 0x00000001260a2450  x15: 0x00000001260a2078
   x16: 0x00000001981c6324  x17: 0x000000000000001e  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000104c2e2e8  x22: 0x000000016b1da330  x23: 0x000000016b1da220
   x24: 0x00000001df983530  x25: 0x0000000000000000  x26: 0x0000000000000010  x27: 0x00006000032bfc90
   x28: 0x0000000125f11790   fp: 0x000000016b1da660   lr: 0x0000000104c2ccc8
    sp: 0x000000016b1da220   pc: 0x0000000104c2d67c cpsr: 0x60001000
   far: 0x00000001dfdc26f8  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x112100000 -        0x11210bfff libobjc-trampolines.dylib (*) <562f95b3-8118-3d61-a13f-34e819dd863d> /usr/lib/libobjc-trampolines.dylib
       0x104c24000 -        0x104c37fff com.alptugan.icns-creator (1.2) <adb8b78b-2cbc-32f1-ba93-0dcfe056c406> /Applications/icns creator.app/Contents/MacOS/icns creator
       0x1b2d4e000 -        0x1b4b1dfff com.apple.SwiftUI (5.0.83.1.405) <27e26874-864d-398c-9050-b379accd2cec> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
       0x18be8b000 -        0x18d19bfff com.apple.AppKit (6.9) <a4e78dd1-6b6e-3f57-924a-4a6a2e679789> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x18828f000 -        0x188322873 dyld (*) <ffd8ab66-c9ab-31df-ab80-3a3dff367ddd> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x197e39000 -        0x198378fff libswiftCore.dylib (*) <9d952ae1-e049-3444-96e3-0a5756c0b89d> /usr/lib/swift/libswiftCore.dylib
       0x188608000 -        0x188614ff3 libsystem_pthread.dylib (*) <e4debb6e-421d-33d0-9e17-77ae0e0fe4dc> /usr/lib/system/libsystem_pthread.dylib
       0x1885cd000 -        0x188607fef libsystem_kernel.dylib (*) <a7d3c07d-0a1e-3c4c-8fba-66905e16bf99> /usr/lib/system/libsystem_kernel.dylib
       0x18866e000 -        0x188b44fff com.apple.CoreFoundation (6.9) <a68b8c77-1dbd-35b0-83fe-42ad58dd6629> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)
Writable regions: Total=1.4G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.4G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
AttributeGraph Data               1024K        1 
CG image                            48K        2 
ColorSync                          576K       27 
CoreAnimation                      688K       43 
CoreGraphics                        32K        2 
CoreGraphics (reserved)             16K        1         reserved VM address space (unallocated)
CoreUI image data                 1392K        8 
Foundation                          16K        1 
Image IO                          4096K        1 
Kernel Alloc Once                   32K        1 
MALLOC                             1.4G       59 
MALLOC guard page                  288K       18 
STACK GUARD                       56.1M        7 
Stack                             11.2M        7 
VM_ALLOCATE                        128K        8 
__AUTH                            1454K      259 
__AUTH_CONST                      23.7M      443 
__CTF                               824        1 
__DATA                             9.9M      429 
__DATA_CONST                      21.4M      448 
__DATA_DIRTY                      1292K      139 
__FONT_DATA                        2352        1 
__LINKEDIT                       886.5M        3 
__OBJC_RO                         70.6M        1 
__OBJC_RW                         2153K        1 
__TEXT                           528.8M      466 
dyld private memory                272K        2 
mapped file                      193.2M       38 
shared memory                      848K       13 
===========                     =======  ======= 
TOTAL                              3.1G     2432 
TOTAL, minus reserved VM space     3.1G     2432 

-----------
Full Report
-----------

{"app_name":"icns creator","timestamp":"2023-10-11 18:50:58.00 -0700","app_version":"1.2","slice_uuid":"adb8b78b-2cbc-32f1-ba93-0dcfe056c406","build_version":"1","platform":1,"bundleID":"com.alptugan.icns-creator","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.0 (23A344)","roots_installed":0,"name":"icns creator","incident_id":"22E7F074-1FA0-4BAA-97C8-368151A03FA2"}
{
  "uptime" : 270000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,2",
  "coalitionID" : 28161,
  "osVersion" : {
    "train" : "macOS 14.0",
    "build" : "23A344",
    "releaseType" : "User"
  },
  "captureTime" : "2023-10-11 18:50:58.4077 -0700",
  "codeSigningMonitor" : 1,
  "incident" : "22E7F074-1FA0-4BAA-97C8-368151A03FA2",
  "pid" : 26948,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-10-11 18:50:52.2282 -0700",
  "procStartAbsTime" : 6549875537356,
  "procExitAbsTime" : 6550023671829,
  "procName" : "icns creator",
  "procPath" : "\/Applications\/icns creator.app\/Contents\/MacOS\/icns creator",
  "bundleInfo" : {"CFBundleShortVersionString":"1.2","CFBundleVersion":"1","CFBundleIdentifier":"com.alptugan.icns-creator"},
  "storeInfo" : {"deviceIdentifierForVendor":"6AADF948-1B80-5640-86E5-9C095688661C","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.alptugan.icns-creator",
  "crashReporterKey" : "2E52B21F-E5AD-9BDE-FAB5-61642DAD7A07",
  "codeSigningID" : "com.alptugan.icns-creator",
  "codeSigningTeamID" : "DUF52Z4557",
  "codeSigningFlags" : 1644167681,
  "codeSigningValidationCategory" : 3,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"oINW+AcaAJS\/QwHR\/XtFqfRPRKn2V0Op+F9CqfpnQan8b8aowANf1g==","atPC":"IAAg1CAAINT8b7qp+mcBqfhfAqn2VwOp9E8Eqf17Ban9QwGR\/8MA0Q=="},
  "wakeTime" : 7568,
  "sleepWakeUUID" : "3A619A88-4944-4894-859F-11CD2EEBF295",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x0000000104c2d67c","rawCodes":[1,4374845052],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":26948},
  "os_fault" : {"process":"icns creator"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":3222624,"threadState":{"x":[{"value":6092071456},{"value":103079215107},{"value":1},{"value":1},{"value":77309411331},{"value":1},{"value":0},{"value":1},{"value":18446744065119617024},{"value":103079215107},{"value":94489280515},{"value":0},{"value":0},{"value":16},{"value":4933166160},{"value":4933165176},{"value":6846964516,"symbolLocation":0,"symbol":"swift_release"},{"value":30},{"value":0},{"value":0},{"value":0},{"value":4374848232},{"value":6092071728},{"value":6092071456},{"value":8046261552,"symbolLocation":16928,"symbol":"InitialAllocationPool"},{"value":0},{"value":16},{"value":105553169480848},{"value":4931524496}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4374842568},"cpsr":{"value":1610616832},"fp":{"value":6092072544},"sp":{"value":6092071456},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4374845052,"matchesCrashFrame":1},"far":{"value":8050714360}},"queue":"com.apple.main-thread","frames":[{"imageOffset":38524,"imageIndex":1},{"imageOffset":35228,"imageIndex":1},{"imageOffset":25969032,"imageIndex":2},{"imageOffset":18656672,"imageIndex":2},{"imageOffset":18782176,"imageIndex":2},{"imageOffset":17202128,"imageIndex":2},{"imageOffset":25894276,"imageIndex":2},{"imageOffset":25892156,"imageIndex":2},{"imageOffset":18682256,"imageIndex":2},{"imageOffset":18682500,"imageIndex":2},{"imageOffset":1963660,"symbol":"-[NSApplication(NSResponder) sendAction:to:from:]","symbolLocation":460,"imageIndex":3},{"imageOffset":5506260,"symbol":"__40-[NSControl _sendActionsForEvents:view:]_block_invoke","symbolLocation":216,"imageIndex":3},{"imageOffset":5505964,"symbol":"-[NSControl _sendActionsForEvents:view:]","symbolLocation":216,"imageIndex":3},{"imageOffset":1951960,"symbol":"NSControlTrackMouse","symbolLocation":1616,"imageIndex":3},{"imageOffset":1950300,"symbol":"-[NSCell trackMouse:inRect:ofView:untilMouseUp:]","symbolLocation":144,"imageIndex":3},{"imageOffset":1949972,"symbol":"-[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:]","symbolLocation":488,"imageIndex":3},{"imageOffset":1947112,"symbol":"-[NSControl mouseDown:]","symbolLocation":448,"imageIndex":3},{"imageOffset":1942452,"symbol":"-[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:]","symbolLocation":3472,"imageIndex":3},{"imageOffset":1465196,"symbol":"-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]","symbolLocation":364,"imageIndex":3},{"imageOffset":1464364,"symbol":"-[NSWindow(NSEventRouting) sendEvent:]","symbolLocation":284,"imageIndex":3},{"imageOffset":8440840,"symbol":"-[NSApplication(NSEventRouting) sendEvent:]","symbolLocation":1556,"imageIndex":3},{"imageOffset":4587964,"symbol":"-[NSApplication _handleEvent:]","symbolLocation":60,"imageIndex":3},{"imageOffset":185440,"symbol":"-[NSApplication run]","symbolLocation":512,"imageIndex":3},{"imageOffset":18184,"symbol":"NSApplicationMain","symbolLocation":880,"imageIndex":3},{"imageOffset":883012,"imageIndex":2},{"imageOffset":9834516,"imageIndex":2},{"imageOffset":14136412,"imageIndex":2},{"imageOffset":41172,"imageIndex":1},{"imageOffset":24664,"symbol":"start","symbolLocation":2224,"imageIndex":4}]},{"id":3222639,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6092632064},{"value":4355},{"value":6092095488},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6092632064},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6583000616},"far":{"value":4659953672}}},{"id":3222640,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6093205504},{"value":8195},{"value":6092668928},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6093205504},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6583000616},"far":{"value":4659953672}}},{"id":3222654,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6094352384},{"value":32779},{"value":6093815808},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6094352384},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6583000616},"far":{"value":4674306048}}},{"id":3222655,"name":"com.apple.NSEventThread","threadState":{"x":[{"value":268451845},{"value":21592279046},{"value":8589934592},{"value":191396627611648},{"value":0},{"value":191396627611648},{"value":2},{"value":4294967295},{"value":18446744073709550527},{"value":44563},{"value":0},{"value":1},{"value":44563},{"value":189408},{"value":0},{"value":0},{"value":18446744073709551569},{"value":8198819920},{"value":0},{"value":4294967295},{"value":2},{"value":191396627611648},{"value":0},{"value":191396627611648},{"value":6094921832},{"value":8589934592},{"value":21592279046},{"value":21592279046},{"value":4412409862}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6582832432},"cpsr":{"value":4096},"fp":{"value":6094921680},"sp":{"value":6094921600},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6582757556},"far":{"value":4345987072}},"frames":[{"imageOffset":6324,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":8},{"imageOffset":81200,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":8},{"imageOffset":42224,"symbol":"mach_msg_overwrite","symbolLocation":476,"imageIndex":8},{"imageOffset":7224,"symbol":"mach_msg","symbolLocation":24,"imageIndex":8},{"imageOffset":515792,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":9},{"imageOffset":509848,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":9},{"imageOffset":506924,"symbol":"CFRunLoopRunSpecific","symbolLocation":608,"imageIndex":9},{"imageOffset":1456352,"symbol":"_NSEventThread","symbolLocation":144,"imageIndex":3},{"imageOffset":28724,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":7},{"imageOffset":7740,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":3222687,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6093778944},{"value":22815},{"value":6093242368},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6093778944},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6583000616},"far":{"value":5243980088}}},{"id":3222688,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6095499264},{"value":0},{"value":6094962688},{"value":0},{"value":278532},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6095499264},"esr":{"value":0,"description":" Address size fault"},"pc":{"value":6583000616},"far":{"value":0}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4598005760,
    "size" : 49152,
    "uuid" : "562f95b3-8118-3d61-a13f-34e819dd863d",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4374806528,
    "CFBundleShortVersionString" : "1.2",
    "CFBundleIdentifier" : "com.alptugan.icns-creator",
    "size" : 81920,
    "uuid" : "adb8b78b-2cbc-32f1-ba93-0dcfe056c406",
    "path" : "\/Applications\/icns creator.app\/Contents\/MacOS\/icns creator",
    "name" : "icns creator",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7295262720,
    "CFBundleShortVersionString" : "5.0.83.1.405",
    "CFBundleIdentifier" : "com.apple.SwiftUI",
    "size" : 31260672,
    "uuid" : "27e26874-864d-398c-9050-b379accd2cec",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/Versions\/A\/SwiftUI",
    "name" : "SwiftUI",
    "CFBundleVersion" : "5.0.83.1.405"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6642249728,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 19992576,
    "uuid" : "a4e78dd1-6b6e-3f57-924a-4a6a2e679789",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2487"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6579351552,
    "size" : 604276,
    "uuid" : "ffd8ab66-c9ab-31df-ab80-3a3dff367ddd",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6843240448,
    "size" : 5505024,
    "uuid" : "9d952ae1-e049-3444-96e3-0a5756c0b89d",
    "path" : "\/usr\/lib\/swift\/libswiftCore.dylib",
    "name" : "libswiftCore.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6582992896,
    "size" : 53236,
    "uuid" : "e4debb6e-421d-33d0-9e17-77ae0e0fe4dc",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6582751232,
    "size" : 241648,
    "uuid" : "a7d3c07d-0a1e-3c4c-8fba-66905e16bf99",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6583410688,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5074944,
    "uuid" : "a68b8c77-1dbd-35b0-83fe-42ad58dd6629",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "2048.1.403"
  }
],
  "sharedCache" : {
  "base" : 6578601984,
  "size" : 4012523520,
  "uuid" : "7906534c-5d2b-3ba8-b9c6-93a5cf1b7b50"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)\nWritable regions: Total=1.4G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.4G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nAttributeGraph Data               1024K        1 \nCG image                            48K        2 \nColorSync                          576K       27 \nCoreAnimation                      688K       43 \nCoreGraphics                        32K        2 \nCoreGraphics (reserved)             16K        1         reserved VM address space (unallocated)\nCoreUI image data                 1392K        8 \nFoundation                          16K        1 \nImage IO                          4096K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                             1.4G       59 \nMALLOC guard page                  288K       18 \nSTACK GUARD                       56.1M        7 \nStack                             11.2M        7 \nVM_ALLOCATE                        128K        8 \n__AUTH                            1454K      259 \n__AUTH_CONST                      23.7M      443 \n__CTF                               824        1 \n__DATA                             9.9M      429 \n__DATA_CONST                      21.4M      448 \n__DATA_DIRTY                      1292K      139 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       886.5M        3 \n__OBJC_RO                         70.6M        1 \n__OBJC_RW                         2153K        1 \n__TEXT                           528.8M      466 \ndyld private memory                272K        2 \nmapped file                      193.2M       38 \nshared memory                      848K       13 \n===========                     =======  ======= \nTOTAL                              3.1G     2432 \nTOTAL, minus reserved VM space     3.1G     2432 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "83d2c57c5237f92cf89d8ff8a9ce16a25923bc2a",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "632e3f9c01482c74ed76392d",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "6503961a9211457059189734"
      },
      "deploymentId" : 240000255
    },
    {
      "rolloutId" : "6297d96be2c9387df974efa4",
      "factorPackIds" : {

      },
      "deploymentId" : 240000014
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000017
    }
  ]
}
}

Model: Mac14,2, BootROM 10151.1.1, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M2, Apple M2, Built-In
Display: Color LCD, 2560 x 1664 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Micron
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Aug  8 2023 04:27:44 version 20.10.1062.3.8.7.162 FWID 01-8e237e8f
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: Laptop, Apple Inc.
Thunderbolt Bus: Laptop, Apple Inc.
</pre>
</details>

![arc.png](https://github.com/alptugan/icns-creator/assets/627/4a1f30f7-c0a9-4419-891f-96c9ef01a65a)

**Comment by alptugan** [comment]
@bigethan thanks for the feedback. 
Do you load the image via drag & drop? If so, can you try using "Browse" button?

**Comment by alptugan** [comment]
uploaded fixed version. It should work using either "drag & drop" or "Browse" button.

**Comment by bigethan** [comment]
I was indeed dragging and dropping - it's working now! thanks so much ❤️
