### ISSUE TITLE
1024x1024

### ISSUE THREAD

**Issue by creativehelm** [alptugan/icns-creator#3]
Hi there,

Any chance you can add 1024x1024 to the list of sizes?

Sincere thanks for this handy app!

**Comment by alptugan** [comment]
Actually, it was available. Gonna fix it in the next release!

**Comment by alptugan** [comment]
@creativehelm updated! Now supports 1024x1024 px icns export as well. Thank you for notifying.
[Latest Release v2.1](https://github.com/alptugan/icns-creator/releases/tag/v2.1)
