### ISSUE TITLE
Generated icons doesn't look like a native ones

### ISSUE THREAD

**Issue by vanfaktor** [alptugan/icns-creator#5]
The icons are missing rounded corners and the size is wrong - they are a little bit bigger than regular one

**Comment by alptugan** [comment]
The app doesn't have such feature. The app just handles the incs conversion process.
Rounded corners can be added as a feature in future releases. 
Can you provide screenshot or images for the wrong image size?

**Comment by vanfaktor** [comment]
Sure. 
<img width="342" alt="Screenshot 2024-08-11 at 13 56 23" src="https://github.com/user-attachments/assets/7a80bbbe-3f95-4286-befa-a40e94a22da5">
I really miss rounded corners. Right now I have to use a different app for that and after that I'm just dragging the png onto the "Get info" app icon

**Comment by alptugan** [comment]
I will check the size issues. 
The interface misleads I guess. I will add round-corner as an optional feature. Good catch! Thanks for that. 
It can be added in future releases. 
The major release also handle that "Get Info" method. It is in my to-do list.

**Comment by vanfaktor** [comment]
Great! Your app has a potential to be probably the best app of this type. I will be waiting for next update

**Comment by dmca-glasgow** [comment]
I found this issue too then realised I need to prepare my image using an Apple design resource:
https://developer.apple.com/design/resources/#macos-apps

Hope this helps.

**Comment by alptugan** [comment]
@dmca-glasgow Yes, you are right (: The visual design of the icon depends on the designer. Because of the application description, it creates an expectation on the user side, I guess (My bad). So I will add optional features to cover the standard Mac OS guidelines, asap. Thanks for the feedback.

**Comment by alptugan** [comment]
v3.3 has fixed these issues. Thanks for your feedbacks.
