### ISSUE TITLE
App not generating ICNS files in MacOS 15

### ISSUE THREAD

**Issue by indros** [alptugan/icns-creator#8]
I realize that MacOS 15 isn't officially supported, but I'm just making the note to share my experience. I was able to download and then install the app after opening the System Settings > Privacy & Security and opening the app through there. I opened a PNG image that loaded up correctly and tried to use the Generate .icns feature, but it doesn't create the files. The original file is in a subfolder of my home directory, so I have read/write access.

**Comment by alptugan** [comment]
Thanks @indros for the feedback.
There is a problem with file save dialog. The generated files are saved to the source image directory. I will fix it asap. 
You can clone the repo and compile the app by yourself. There are instructions for that. For now I do not think to update my system to mac OS 15.

Is your Mac M1-2 or Intel-based, btw?

**Comment by indros** [comment]
I'm using the app on Mac OS 15 on an M1 Macbook Pro.

**Comment by yanglb** [comment]
Had the same problem on Macos 15, but it worked fine after removing the special symbols (the spaces) in the icon file name.

`code solid.svg` - failed.
`code-solid.svg` - success.
